/*
 * BIP39 — Mnemonic code for generating deterministic keys.
 *
 * Reference: https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki
 *
 * This module only generates mnemonics from external entropy.
 * It does NOT validate existing mnemonics in this minimal impl, but
 * mnemonic_to_seed() does PBKDF2 derivation as specified.
 */
#ifndef TRI_PAPER_BIP39_H
#define TRI_PAPER_BIP39_H

#include <stdint.h>
#include <stddef.h>

/* Generate a 12- or 24-word mnemonic from internal OS entropy.
 * Returns 0 on success. The mnemonic is space-separated words in 'out'. */
int bip39_generate(int n_words, char *out, size_t out_len);

/* Convert a mnemonic to a 64-byte BIP39 seed via PBKDF2-HMAC-SHA512.
 * mnemonic_passphrase is the optional "25th word" (NULL/"" = none). */
int bip39_mnemonic_to_seed(const char *mnemonic,
                           const char *passphrase,
                           uint8_t seed[64]);

/* Validation/test helper: returns 1 if `word` is a valid BIP39 English word.
 * Exposed so callers (and tests) can sanity-check generated mnemonics. */
int bip39_is_known_word(const char *word);

/* Returns 1 if `mnemonic` is 12 or 24 BIP39 English words AND its checksum
 * (encoded in the last word) matches the SHA-256(entropy)[0:chk_bits].
 * Returns 0 otherwise. Does NOT verify the seed was generated by us, only
 * that BIP39 validation passes. */
int bip39_validate_mnemonic(const char *mnemonic);

/* Returns the n-th BIP39 word (0..2047) or NULL on out-of-range.
 * Used by tests to access the wordlist without exposing the static data. */
const char *bip39_word(int n);

/* Wordlist size (always 2048 for the English wordlist). */
#define BIP39_WORDS 2048

#endif
